### PR TITLE
Spirit trees

### LINKED ISSUE #2: spirit trees in place of seed pods
maybe have spirit trees for gnome area instead of seed pods as a alternative

### PR DESCRIPTION
**Pull request by othyn**
Closes #2, kinda. It only implements Spirit Tree's, not Fairy Rings.

**This PR includes all changes from #6, as it uses #6 as a base branch. So please merge #6 before this.** Sorry for the bad branch etiquette on this one...

Adds initial support for Spirit Tree's.

Working:
- Teleport step.
- Works as a valid stop in the process so you can complete a farm run using it.

Not working:
- Highlighting the Spirit Tree Game Object in the world, I have no idea how to find its ID and Google/DDG didn't help. Maybe I should try ChatGPT...

### CODE REVIEW

**Comment by Speaax** [comment]
image
By adding --developer-mode to your configurations you will get a new plugin called Developer tools.

image

image

I'm looking at the code and testing it now btw.

**Comment by Speaax** [comment]
The Spirit tree group/child id wont work to highlight the teleport options. I had the same issue with a few widgets. I think highlightDynamicComponent in FarmingTeleportOverlay does the job if I don't remember wrong. 

Widget widget = client.getWidget(187, 3);
highlightDynamicComponent(graphics, widget, 1, leftClickColorWithAlpha);

Just need to place 1 with the correct value. From the top going down it start's at 0 and increments by 1 for each teleport option.

I can fix this myself as I catch up with you.

**Comment by othyn** [comment]
Oh sweet! Thanks, thats super helpful. I was looking for a mode like that in RuneLite

**Comment by othyn** [comment]
Thanks for the merge!

**Pull request merged**
