### PR TITLE
Fix for teleport name selection if it differs to the location name

### PR DESCRIPTION
**Pull request by othyn**
This fixes the teleport options by allowing an override to be specified if the teleport name differs to the location name.

### CODE REVIEW

**Comment by Speaax** [comment]
Should this method be extended to Spirit trees as well?

**Comment by othyn** [comment]
Good shout, I rejig a few things

**Comment by Speaax** [comment]
"Portal_Nexus_Camelot" could also use this. I wont make a commit for it considering it went straight trough last time x)

**Comment by othyn** [comment]
Haha, although `Portal_Nexus_Camelot` already has `.overrideLocationName("Camelot")` assigned

**Comment by Speaax** [comment]
My bad, Portal_Nexus_Camelot in HerbRunItemAndLocation :p

**Comment by othyn** [comment]
Ah... thanks, yep I'll add that too!

**Comment by othyn** [comment]
Just testing the latest commits, will let you know if its all good

**Comment by Speaax** [comment]
Not relevant here, but I'll be adding a few issues I'm aware of and some suggestions of features. Don't feel the need to do those, as you're already adding in other features that's also needed. This is just to have a log of features/bugs etc I'm aware of, so there can be some structure other than in my head. Probably have forgotten a thing or two over the months it's been out.

I will also try and add more branches as I'm doing things, as up until now i have just had all my progress local until its been done and ready to be added to master.

**Comment by othyn** [comment]
Sounds like a good plan, I make heavy use of GitHub issues on all my repos as a brain dump for things I would like to implement on them. Thanks for the heads up!

**Comment by othyn** [comment]
All appears good now btw, tested against the Portal Nexus and Spirit Trees, looks to be working fine

**Comment by othyn** [comment]
Thanks for the merge!

**Pull request merged**
