### PR TITLE
Spirit tree alternative teleport refactor

### PR DESCRIPTION
**Pull request by othyn**
Refactor the spirit tree highlighting into the new method, although nothing is currently using the Falador or Kourend teleports, so its a tiny PR.

Tested working.

### CODE REVIEW

**Comment by Speaax** [comment]
> although nothing is currently using the Falador or Kourend teleports

The other day i had setup for both, and that's why there was code for it. Not sure what happened with it but its not that hard to add them back anyways.

**Comment by Speaax** [comment]
> 'Allow maintainers to make changes'

That make sense then 👍

**Comment by othyn** [comment]
Huh, could be part of that weird merge issue where we lost some code

**Comment by Speaax** [comment]
Might have not merged it either, I'm not sure, was a bit hangover that day x)

**Pull request merged**
