### PR TITLE
Trees pay for protection

### LINKED ISSUE #8: Add a prompt to 'Pay for protection' after planting trees/fruit trees
I have the implementation of this ready to PR, I'm just logging the work as an issue to track.

I just need to wait for my trees to finish growing to test the implementation, lmao.

### PR DESCRIPTION
**Pull request by othyn**
Closes #8.

- Add an option to have a reminder to pay for protection before teleporting onwards to the next patch for trees and fruit trees.
- Store a default macOS run configuration for IntelliJ, as there are some extra options required, so will be helpful to get people up and running on the project quicker
- Fix spirit trees not being highlighted (didn't realise you'd also picked up on it in #9, in the merge conflict I've just rolled the extra ID's you found into the ones I found too, then rolled forwards on the change below)
- Fix spirit trees requiring a home teleport as the first step, instead now it just highlights all spirit trees on the map

### CODE REVIEW

**Comment by Speaax** [comment]
Looks nice. Could you make add an if statement or something to prevent the user from using compost and paying when "Pay for protection" is enabled?

Also after doing Falador elite diary you cannot pay for a protection anymore as its already protected.
image

Also I'm new to using github, so if I do some weird stuff just point it out so I can improve.
Is there any benefits to pointing out some flaws here before accepting the commit, or is it better to just accept the commit and open an Issue to highlight these problems?

**Comment by othyn** [comment]
> Looks nice. Could you add an if statement or something to prevent the user from using compost and paying when "Pay for protection" is enabled?

There is already conditional logic for this, but given you've had that experience, I'm guessing the condition is bugged. Let me do some more testing and see if I can reproduce the issue.

> Also after doing Falador elite diary you cannot pay for a protection anymore as its already protected.

Thanks for sharing the string for that, as I'm a million miles away from completing the hard diaries 😂

I'll get that added to the potential strings to signify payment.

> Also I'm new to using github, so if I do some weird stuff just point it out so I can improve.
Is there any benefits to pointing out some flaws here before accepting the commit, or is it better to just accept the commit and open an Issue to highlight these problems?

It's down to the repo maintainer to establish a 'contribution guide', but my advice would be that you follow a standard practice of rejecting a PR until it meets your standards for the repo for merging. That being all bugs/issues fixed first within the PR of the merging code, prior to the PR being accepted and merged.

So in this case, you've done the right thing. You've outlined what I need to fix prior to the PR being accepted and merged, as you are maintaining the repo's integrity. This step is usually called 'code/PR review', its why you have 'Reviewers' and 'Assignees' for PR's, and a detailed diff. The Assignee would be the PR owner, and the Reviewer(s) would be the repo maintainer(s). Once my code is up to standard and all bugs are patched, we can review again and if everything is okay, go ahead and accept the PR and merge.

Code reviews are excellent purely because a fresh pair of eyes will always find something that the assignee didn't. I've been in software dev for around a decade, have colleagues and friends with a lot more and a lot less experience - but code reviews always reveal something, regardless of experience. Always a good opportunity to learn! 

So you've done things how I run my repos at least, although not saying that is in anyway the be-all-end-all of ways to run things, just advice that you can take or leave 😄

**Comment by othyn** [comment]
> Looks nice. Could you add an if statement or something to prevent the user from using compost and paying when "Pay for protection" is enabled?

✅ This bug has now been fixed.

> Also after doing Falador elite diary you cannot pay for a protection anymore as its already protected.

✅ This bug has now been fixed.

**Comment by Speaax** [comment]
image

"[Fix highlight bug on patches requiring compost](https://github.com/Speaax/Farming-Helper/pull/10/commits/1356f5c40c73e1ebb702a85dbcbb5151a17c0d47)" came with another issue for herb runs at least. both herb/flower patch will be highlighted at the same time.

Also the color highlights seems to be a bit all over the place. I would like to maintain the color code i have been going with. While it does need changes the current changes made it seem a bit mismatched. 

If you want to make changes to highlight colors here is the structure I would prefer to have:
- 'Use' item color(default purple): Current use it to highlight 2 components at the same time, Like a compost bucket/seeds and the patch its supposed to be used on. 
- Left click(default green): Anything that just requires a left click except where the "use" option is applied.
- Right click(default blue): Whenever you need to right click to select an option, like on a Ardougne cloak to select "Farm Teleport". 

The current implementation is flawed and doesn't respect the menu entry swapper plugin where the user can change left click options on items and objects. 

There is most likely a simple way to check what option is the first one on an item/gameObject and dynamically change to left/right click highlights. If the rightClickOption from Teleports is matching the first option on an item we could highlight it in green, and if not we highlight it in blue?

I'm guessing that's the best way to go about it, but i wouldn't know. 

Other than that payments looks to work as expected now 👍 
Happy to accept the PR once the correct patch is highlighted for composting and when color highlights follow the given structure above or reversed to the old one.

**Comment by Speaax** [comment]
I did see that some of the highlight functions didn't the color option like highlightDynamicComponent since its always left click, but itemHighlight need the options for left, right and use(Royal seed pod is left click, Ardougne cloak is right click to select "Farm Teleport and use is needed for seed/compost), and patches need left click and use colors(left click when farming, use when highlighting seeds/compost). 

Thanks for the commits in general tho, a lot of the code looks a lot better ^^

**Comment by Speaax** [comment]
I guess I can individually reject a commit, so I could just not accept the commit with the color highlights?

**Comment by othyn** [comment]
PR's are on a accept/reject 'the whole thing' deal, not per-commit.

I'm refactoring the code again to ensure all the correct colours are in place, no worries. Updated PR should be live in an hour-or-so, hold tight 👍

**Comment by Speaax** [comment]
> PR's are on a accept/reject 'the whole thing' deal, not per-commit.
I see, learning new things about github every day these days xD

Also currently all the PR is to the master, this is the one used for plugin hub, would it be better practice to set up another branch and merge/rebase it to the master once its ready for a PR for the plugin hub?

**Comment by othyn** [comment]
> I see, learning new things about github every day these days xD

Haha no worries, it can be quite daunting to be faced with a Git workflow when you're not familiar with it.

> Also currently all the PR is to the master, this is the one used for plugin hub, would it be better practice to set up another branch and merge/rebase it to the master once its ready for a PR for the plugin hub?

Your thinking is correct! Ideally you'd have a `main` or `master` branch which mirrors whats in production, then a `dev` branch in which acts as the merge branch for all of your `feature`/`bug` development branches (which are based from `dev`). You then PR `feature`/`bug` branches into `dev`, then when you are ready to release, PR `dev` into `main` or `master`.

**Comment by Speaax** [comment]
Ok after this PR is completed I will set up a dev branch. 

You plan on doing a lot of commits for the project, or are you just adding some features you'd like to see in this plugin?

**Comment by othyn** [comment]
Just done a herb run with that colour patch fix, we should be good to go 👍 

> Ok after this PR is completed I will set up a dev branch.

Super!

> You plan on doing a lot of commits for the project, or are you just adding some features you'd like to see in this plugin?

Not sure haha still have a few things I'm working on and have branches/PR's queued up for with prototypes/partial implementations:
- Hardwood/Fossil Island tree support
- Fairy ring support
- 
- Make 'pay for removal' an option
    - I have half of this working, the half that isn't is the required items check for the axes, as at the moment there isn't a system in place for only requiring one item from a given set of items - currently working on it
- Refactoring the system of Location definitions

**Comment by Speaax** [comment]
> * Figure out a solution for handling highlighting of Teleport options on interfaces where the required destination doesn't align with the Location (e.g. Camelot for Catherby, Falador for Taverly)

If you look at the current implementation on gettingToLocation case SPIRIT_TREE I did make a quick workaround for spirit trees, and i assume it would work in the case PORTAL_NEXUS as well. If you cant find a way to do it its a nice temporarily quick implementations. 

I'll check out the code now.

**Comment by othyn** [comment]
> If you look at the current implementation on gettingToLocation case SPIRIT_TREE I did make a quick workaround for spirit trees, and i assume it would work in the case PORTAL_NEXUS as well. If you cant find a way to do it its a nice temporarily quick implementations.

Super, I'll re-sync my fork's `master` to pull that across

**Comment by Speaax** [comment]
Yeah that make sense. I'll try to make a commit for your branch before I accept the PR. Saw a few issues and i had another version of the spirit tree that has a bit more options for adding some teleport options.

**Comment by othyn** [comment]
Yeah I'm just restoring that code as we speak, not sure what removed it as the git history shows no code removals...

**Comment by Speaax** [comment]
Probably me doing some commits etc messing something up xD

**Comment by Speaax** [comment]
Wait, did that come up properly or did you just accept it instantly? xD

**Comment by othyn** [comment]
Commits are instant, they just go against the PR - so you can see your commit above this message as part of this PR.

At a guess you had a merge conflict? I'm just fixing a few things 😄

**Comment by othyn** [comment]
^ Just pushed a fix with both of our works merged.

> I thought you had to accept my PR for it to show up, thought i posted it to your copy of my repository xD

Okay this is going to be a bit complicated to explain hahah

So my repo is a fork of your repo. There is an open PR on _your_ repo from my forked repo that wants to merge the [trees-pay-for-protection](https://github.com/othyn/Farming-Helper/tree/trees-pay-for-protection) branch on [othyn/Farming-Helper](https://github.com/othyn/Farming-Helper) into your repo on the `master` branch.

So as you made the change directly into the `trees-pay-for-protection` branch on my fork, that commit will be entered straight into the branch as a normal commit. If you wanted to PR any change on my fork, you'd have to create a new branch on my fork and then PR it on my forked repo into `trees-pay-for-protection`.

Trying to explain this without visual aids and over text is really difficult 😂 especially without any background in `git`

> From my PR now or related to the spirit tree thing?

Related to some stale commits in `master` on your repo. I've manually merged everything across between mine and your versions, as a load of stuff was lost again in the merge conflict resolve on your side haha

**Comment by othyn** [comment]
> This was what confused me a little, I didn't realize I could make commits without you accepting or rejecting them :p Is it because you forked my repository that i can commit directly to yours?

Ohhh yeah! Penny just dropped. I have no idea how you were able to do that, as you're not a collaborator on that repo. I've had a look around and can't see anything in which would give you inherent permission over the forks, but it would kinda make sense that that is the case. Odd! But suppose it works in your favour haha

> Just to make sure this is the correct way to update my local code?

Depends. I personally rebase instead of merge, meaning I commit all my local changes first (so local and remote are diverged), then rebase my local onto remote and deal with any conflicts. I just personally think a rebase is cleaner on yet-to-be-remote changes.

But its mainly down to personal preference and if its on remote/shared yet.

**Comment by othyn** [comment]
Thanks for the merge!

**Pull request merged**
